### ISSUE TITLE
卡在clover启动界面

### ISSUE THREAD

**Issue by zitn** [hunkspy/OSX-ThinkPad-S2-3rd-2018#1]
电脑型号是 s2 2018，好像是01cd  
使用的系统镜像是
https://blog.daliansky.net/macOS-Catalina-10.15.5-19F96-Release-version-with-Clover-5118-original-image-Double-EFI-Version-UEFI-and-MBR.html  
用transmac写入u盘，DiskGenius替换EFI文件夹，启动clover之后只有一个图标，按f1有帮助菜单，但是啥都用不了
能帮忙大概看下我这边遇到的是什么问题么......另外请问你这边用的是哪个镜像，能分享下么

**Comment by zitn** [comment]
另外请问你列出的CPU为啥是i3的，我记得s2 2018都是i5-8250U来着

**Comment by hunkspy** [comment]
只看到一个图标应该是Clover驱动的问题，加个FAT的驱动进去应该可以。我这款是单位配发的低配笔记本。i3的。

**Comment by zitn** [comment]
我试试加个驱动，那请问你装的哪个版本系统

**Comment by hunkspy** [comment]
具体版本我忘记了，应该是19年8月份时候的版本。后来就不折腾了，现在改回Windows了。

**Comment by zitn** [comment]
算了算了。。。我也不折腾了
